trigger:
  - main

pool:
  vmImage: 'ubuntu-latest' 

steps:
- task: JavaToolInstaller@0
  displayName: 'Install Java 25'
  inputs:
    versionSpec: '25'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: chmod +x gradlew
  displayName: 'Make gradlew executable'

- script: ./gradlew test
  displayName: 'Run JUnit Tests'

- script: ./gradlew build
  displayName: 'Build Java Package'